spring.application.name=api

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sportradar}
spring.datasource.username=${POSTGRES_USER:user}
spring.datasource.password=${POSTGRES_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
